// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['backend']['UserCrud']['Connect'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['UserCrud']['Startup'](arg1);
}
