// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMetrics(arg1) {
  return window['go']['main']['App']['GetMetrics'](arg1);
}

export function GetTraces(arg1) {
  return window['go']['main']['App']['GetTraces'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
