// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetLogs(arg1:string):Promise<models.LogsQueryRangeResponse>;

export function GetMetrics(arg1:string):Promise<models.MetricsResponse>;

export function GetTraces(arg1:string):Promise<models.TracesQueryRangeResponse>;

export function Greet(arg1:string):Promise<string>;
